steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/figma-proxy-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/figma-proxy-server:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/figma-proxy-server:$COMMIT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'figma-proxy-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/figma-proxy-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/figma-proxy-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/figma-proxy-server:latest'
